### ISSUE TITLE
TypeScript 5.4 build error: eventsQuerySchema.omit() loses types after upgrade

### ISSUE THREAD

**Issue by WEugen** [dubinc/dub#3059]
## Environment
- Next.js: 15.5.4
- TypeScript: 5.4.4 (via pnpm.overrides)
- Dub version: Latest (fresh clone from main)
- OS: Debian 12

## Problem
Build fails with TypeScript errors after upgrading from TS 5.2.2 to 5.4.4.

Error in `apps/web/app/(ee)/api/events/export/route.ts`:

Type error: Property 'domain' does not exist on type '{ page: number; event: "clicks" | "sales" | "leads"; sortBy: "timestamp"; limit: number; ... }'.

Error in `apps/web/app/(partner)/api/partner-profile/programs/[programId]/events/route.ts`:

Type error: Property 'linkId' does not exist on type '{}'.

## Root Cause
`eventsQuerySchema` uses `.omit()` which loses all inherited types in TS 5.4+:

```typescript
export const eventsQuerySchema = analyticsQuerySchema
  .omit({ groupBy: true, sortBy: true })
  .extend({
    event: z.enum(EVENT_TYPES).default("clicks"),
    // ... other fields
  });
```

After `.omit()`, TypeScript no longer infers fields from `analyticsQuerySchema`.

## Question
Is this a known issue? Should I add explicit `.extend()` for all required fields, or is there a better approach for TS 5.4 compatibility?

## Workaround
Adding explicit fields in `.extend()` fixes the issue, but seems verbose. Is this expected?

After .omit(), TypeScript no longer infers fields from analyticsQuerySchema.

Question
Is this a known issue? Should I add explicit .extend() for all required fields, or is there a better approach for TS 5.4 compatibility?
Workaround
Adding explicit fields in .extend() fixes the issue, but seems verbose. Is this expected?

**Comment by Hritwik001** [comment]
Hey @WEugen  @steven-tey  👋
I was able to reproduce this on TypeScript 5.4.4 — looks like the chained call
analyticsQuerySchema.omit(...).extend(...) drops some inherited fields (domain, linkId) in the inferred type under TS 5.4.

🔍 Root Cause: In TS 5.4+, Zod’s type inference after .omit() can lose its link to the base schema’s shape.

💡 Proposed Fix: Recompose eventsQuerySchema from analyticsQuerySchema.shape, then call .omit({ groupBy, sortBy }).
This restores all inherited types while keeping the same runtime behavior.

🧪 Plan:
– Confirm fix locally (already verified in build)
– Open a PR within 24–48 hours with a small type-check test included

Thanks for keeping this project so clean 🙌 — I’ll share the PR soon! 🚀

**Comment by WEugen** [comment]
Thanks for confirming! Spent 2 days thinking I messed up 😅 Looking forward to the PR! 🚀

**Comment by WEugen** [comment]
Sorry, closed by mistake! Will keep it open until the PR is merged 🙏

**Comment by WEugen** [comment]
Hi @Hritwik001 👋

Hope you're doing well! Just checking if there's any update 
on the TypeScript 5.4 + Zod .omit() fix you mentioned.

It’s currently blocking our production deployment, so we wondered 
if you already have a draft or branch we could test — or if we should 
wait for the full PR.

Thanks for your time!

**Comment by Hritwik001** [comment]
@WEugen 
Thanks for checking in! I’ve been working on reproducing and resolving the TypeScript 5.4 + Zod .omit() inference issue locally.

The type-level fix itself is clear — the main delay has been stabilising the monorepo build environment so I can validate it end-to-end before opening the PR.

I’m actively debugging and expect to have a clean local run soon.
I’ll update here once the branch is ready for review.

Appreciate the patience and your understanding 🙏

**Comment by Hritwik001** [comment]
Hi  @WEugen 👋
Just a quick update — I’ve opened a PR for this issue here: [#3080](https://github.com/dubinc/dub/pull/3080)
.
It isolates the TypeScript 5.4 literal inference fix for EventType.
No runtime changes — only preserves the literal union.

Please have a look when convenient 🙏

**Comment by WEugen** [comment]
@Hritwik001 Thanks so much for the PR! 🙌 I pulled the branch and it fixes the eventsQuerySchema/Zod literal-inference issue on TS 5.4 right away—the build now proceeds past those earlier errors. After that it surfaces unrelated strict-null checks (e.g. MenuItem asChild in apps/web/app/(dashboard)/[slug]/(ee)/program/partners/[partnerId]/layout.tsx, bountySubmission null guard, etc.), but those are outside the scope of this fix. So from my side the root cause in #3059 is resolved—really appreciate the quick turnaround!

**Comment by Hritwik001** [comment]
Thanks so much for confirming, @WEugen 🙏
Really glad the TS 5.4 literal inference fix fully resolved the root issue!

I’ve double-checked locally as well — everything looks great.
Feel free to merge this when convenient and close the issue.

Also, I’d love to stay connected beyond GitHub to keep learning and contributing together.
If you’re on LinkedIn , would love to follow your work there too!

Thanks again for the quick turnaround and detailed feedback — really appreciate it! 🚀

**Comment by devkiran** [comment]
@Hritwik001 We just merged a PR that upgrades Zod to v4. Can you try again locally and let me know if you still hit the error?
